# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [20]:
import numpy as np

## Vector operations

In [21]:
u = np.array([2, 4, 5, 6])

In [22]:
# In linear algebra, vectors are typically represented as column vectors. Vector operations are element-wise.
2 * u

array([ 4,  8, 10, 12])

In [23]:
v = np.array([1, 0, 0, 2])

In [24]:
# Vector addition is also element-wise.
u + v

array([3, 4, 5, 8])

In [25]:
# In numpy, multiplication is element-wise.
u * v

array([ 2,  0,  0, 12])

## Multiplication

Dot product  of two vectors is the sum of the element-wise products of the vector elements.
For two vectors u and v, u is usually a column vector and v is a column vector. v has to be transposed for the operation. It is written as (v-transposed)(u):

$v^T$

$\mathbf{v} \cdot \mathbf{u} = \sum_{i=1}^n v_i u_i$

In [26]:
v.shape[0]

4

In [27]:
# implementation of dot product
def vector_vector_multiplication(u, v):
        # Vectors must be same size
        assert u.shape[0] == v.shape[0]
    
        # Number of elements -- both vectors have same size.
        n = u.shape[0]
    
        result = 0.0

        # loop over vector elements from 0 to n-1, multiple corresponding elements and add to result
        for i in range(n):
            result = result + u[i] * v[i]
    
        return result

In [28]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [29]:
# We don't need to implement this ourselves, numpy has it built in:
u.dot(v)

np.int64(14)

Matrix - vector multiplication

For each row of u, do vector-vector multiplication with v (dot product)

The dimensionality of each row of u must match the dimensionality of the vector v



In [30]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [31]:
print(U.shape)
print(v.shape)

(3, 4)
(4,)


In [32]:
def matrix_vector_multiplication(U, v):
    # Number of columns in U must match number of elements in v
    assert U.shape[1] == v.shape[0]

    # number of rows in U
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    # for each row in U, do vector-vector multiplication with v -- calculate dot product
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [33]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [34]:
# dot product handles matrices as well.
U.dot(v)

array([14,  5,  5])

In [35]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [36]:
def matrix_matrix_multiplication(U, V):
    # Number of columns  in U must match rows in V
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [37]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [38]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix
Multiply a matrix by `I` and you get the matrix back.

In [39]:
# Create an identity matrix 3 x 3
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [41]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse
When you multiply a vector by its inverse, you get I.

In [42]:
# Create a square matrix from V by selecting first three rows
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [43]:
# calculate the inverse with the linalg.inv function
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [44]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Next 

Intro to Pandas